### ISSUE TITLE
[Feature Request] Customisable scheduling algorithm

### ISSUE THREAD

**Issue by 1ma** [spiral/roadrunner#141]
### Use Case

We are building an I/O bound REST API that needs to fetch and aggregate data from other 3rd party APIs in real time. During development we found out that for some of these services just establishing a TCP connection and performing the TLS handshake could take to the tune of 500ms-1s, and with a traditional nginx+fpm setup we have to pay this price for every single request coming through our API. Switching to roadrunner makes it possible to leverage persistent HTTP/1.1 connections, so that when a worker manages to reuse pre-established HTTP connections to 3rd parties we are seeing total time savings of up to -70%.

### Problem

Despite this any upstream HTTP server may see fit to close the connections themselves after some period of inactivity, usually at about 30-60 seconds. And since roadrunner allocates the requests to each worker in a round robin fashion, when we have a high number of workers coupled with low traffic any given worker tends to stay enough time inactive for its persistent HTTP connections to time out and lose the time savings.

I believe that for our use case a different scheduling algorithm would work better. One that would always try to allocate requests to the same workers unless they are busy with another one, something like "give the task to the worker with the smallest PID that is not busy right now"<sup>1</sup>.

### Proposal

To that end it would be really helpful to be able to customize roadrunner's scheduling algorithm in its configuration file, something like this:

```yaml
http:
  workers:
    pool:
      scheduling: "round robin" (default) | "other"
```

Our team doesn't have a lot of Golang expertise, but if you like this proposal I guess that with a bit of guidance we could have a stab at contributing this feature ourselves.

1. I reckon this scheduling algorithm must have a well-known name, but I can't seem to find it.

**Comment by wolfy-j** [comment]
Hi, that's an interesting use-case and I will try to think it through in details this weekend.

I have a couple of questions:
1) How unified are API calls you make?
2) Do you have to use PHP curl queries or you change them (a.k.a. do you have any abstraction mechanism which can be easily swapped).

What you are looking for is to alter the `allocateWorker` method in `StaticPool` implementation. This is hard to do since the current implementation is performance optimized stack, but possible.

However, another option you might want to check is to move HTTP calls at the golang end and use RPC server functionality, in this case, PHP would only be responsible for the mapping part of the flow. Since you are going to be relying on the server to make calls keep-alive connections will be shared between workers. The RPC penalty will be irrelevant considering the duration of the calls you make. Plus, the implementation of "CURL" like service in RR is much more straight forward and predictable by behavior (but you have to remember to set the max timeout on HTTP client in golang!).

**Comment by wolfy-j** [comment]
FYI, the current mechanism is not round robin. It's stack in a FIFO form.

**Comment by 1ma** [comment]
1. Each request to our API usually leads to 5-20  external HTTP requests to 1-3 different services (but these numbers are expected to grow), and are currently serving about 1.5 million daily requests. At the idlest times of the day we may still handle less that 1rps.

2. Yes, we are using an internally developed library that is an abstraction over [curl_multi](https://www.php.net/manual/en/function.curl-multi-init.php), and the actual implementation can be swapped because it implements an interface. It can send as much requests as we need concurrently, but their parsing is sequential. Nevertheless we managed to optimize the app to a point where over 99% of the time is spent inside [curl_multi_select](https://www.php.net/manual/en/function.curl-multi-select.php) waiting for the remaining requests to finish.

**Comment by wolfy-j** [comment]
OK. Have you considered the approach I suggest? In this case, you might achieve even better performance by reusing shared connection pool. It won't be complex to implement functionality similar to curl_multi_select on golang, but it depends on what type of calls you make.

**Comment by wolfy-j** [comment]
If this approach won't work I can think of how to achieve allocation approach you would like to use.
