### ISSUE TITLE
Try to terminate worker before killing

### ISSUE THREAD

**Issue by lda** [spiral/roadrunner#146]
Wouldn't it be better to send a TERM signal before killing the worker process on maxExecutionTTL? You already have such code in StaticPool.destroyWorker. Is it ok to open Pool.DestroyWorker and call this method instead of killing process?

**Comment by lda** [comment]
I'm talking about [this code](https://github.com/spiral/roadrunner/blob/master/service/limit/controller.go#L69)

**Comment by wolfy-j** [comment]
ExecTTL used to kill stuck workers during the execution of a specific task, graceful shutdown is not possible since the worker won't accept any command during execution state. So, technically, we can use `destroyWorker` but this is internal pool functionality. Also, it will cause additional `destroyTimeout` to be fired.

**Comment by lda** [comment]
Ok, I just checked it out and found that you were right. Thank you for your explanation.
