### ISSUE TITLE
[Feature Request] Healthz port

### ISSUE THREAD

**Issue by awprice** [spiral/roadrunner#192]
It would be great to have a HTTP server on a seperate address/port that can be used for health checking road runner and whether it is ready to serve traffic to the workers.

Currently I am sending my health check traffic to the main http address, this is undesirable for a variety of reasons:
 - Clutters access logs with healthz requests
 - Places unnecessary load on the PHP workers
 - Request metrics include healthz requests

Example configuration:
```yaml
healthz:
  address: 0.0.0.0:8080
```

This would be useful for a variety of use cases, such as [Kubernetes readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes), [AWS ALB health checks](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html) or [GCE load balancer health checks ](https://cloud.google.com/load-balancing/docs/health-checks).

**Comment by wolfy-j** [comment]
Hi, you can ping the metrics port itself. But module like that is easy to build, so if anyone wants to help we will merge it into root package.

**Comment by awprice** [comment]
@wolfy-j Ideally the healthz endpoint would only return `200 OK` if the PHP workers are ready to accept requests. Does the metrics endpoint support this?

**Comment by wolfy-j** [comment]
Nope. So you are correct, you can request http dependency and use Server() method to get list of workers.

**Comment by awprice** [comment]
@wolfy-j Thanks! I'll have a look into this and come up with something.

**Comment by frickenate** [comment]
@wolfy-j Is the health service a feature that will automatically port to and work with [spiral/php-grpc](https://github.com/spiral/php-grpc) the next time that project updates its dependency on RR? Is RR's "worker pool" abstracted such that this health service will work for both http and grpc services, or would that require additional grpc-specific development?

**Comment by wolfy-j** [comment]
Yeah, we can port it for sure or make it universal. You can create a ticket :)

**Comment by wolfy-j** [comment]
We can make it like we did "limit" service, so you can connect to any compatible service.

**Comment by frickenate** [comment]
My Go is too basic to help out, but from my understanding it looks like there will be more work to do, as the health service currently [stores a pointer to the http-specific service in its struct type](https://github.com/spiral/roadrunner/pull/193/files#diff-d0c66b5211c4e375341a73e9eba11ee0R19) so that the [ `isHealthy` method](https://github.com/spiral/roadrunner/pull/193/files#diff-d0c66b5211c4e375341a73e9eba11ee0R64) can access its worker pool. If the grpc service's worker pool instance is of the same type as the http one, the struct and the [`Init()` method](https://github.com/spiral/roadrunner/pull/193/files#diff-d0c66b5211c4e375341a73e9eba11ee0R23) could be modified to store a pointer to the worker pool itself rather than a particular http/grpc/etc service. The `isHealthy` method would then operate directly on the worker pool in a service-agnostic fashion.

This assumes that the http and grpc services share an identical type or interface that allows calling `.Server().Pool().Workers()` on them, and that the pool object itself is not replaced (destroyed + recreated) for the lifetime of the process. If those assumptions are wrong... then even more work to differentiate http vs. grpc health service. In any case, the health service itself would remain as the existing http server.

Should I create a ticket in this repo, or in the grpc one to start?

**Comment by wolfy-j** [comment]
Take a look as Limit service (https://github.com/spiral/roadrunner/blob/master/service/limit/service.go#L23). It uses rr Container (IoC). You can fetch all the available services and only use ones which are matching the interface. 

You need an interface that matches on `func (s *Service) Server() *roadrunner.Server`.
