### ISSUE TITLE
[RR2] Custom logger

### ISSUE THREAD

**Issue by Smolevich** [spiral/roadrunner#208]
How we can customize logs and change severity? I mean mechanism like [here](https://roadrunner.dev/docs/library-event-listeners)

**Comment by wolfy-j** [comment]
You can assign custom logger to rr.Logger during the boot or create custom even handlers.

**Comment by Smolevich** [comment]
For this cases i should use roadrunner as library?

**Comment by wolfy-j** [comment]
Yes, or you can redefine it on the application level. A proper logging module is an effort we look to implement next year.

**Comment by wolfy-j** [comment]
See: https://github.com/spiral/roadrunner/blob/master/cmd/rr/http/debug.go#L22

You can listen and log any service. We can also look at implementing logger service to the consumer logrus stream and save it into different files/streams. However, we will have to dig into logrus api first.

**Comment by Smolevich** [comment]
Useful case for us - throw log events catched from php://stderr by roadrunner as is.

**Comment by wolfy-j** [comment]
We need another log listener instead of logrus for that.

**Comment by l0gicgate** [comment]
@wolfy-j is there a way to tie into the logger within the `worker.php` file and set log levels? Currently I'm outputting to `php://stderr` but the formatting from my Monolog handler gets removed within the `stdout` logs and they show up as `WARN`:
<img alt="example" src="https://puu.sh/G9cUE/949bb22eb9.png" />

**Comment by wolfy-j** [comment]
This is something we are def going to improve in 2.0 version. At the moment you can only send text stream to RR so there are no way to group it by the worker. I would recommend using default Monolog handlers in addition to STDERR.

**Comment by l0gicgate** [comment]
@wolfy-j I’m currently using Slim 4 and the StreamRelay/PSR7 Client only to run my my app. I looked at the docs and it didn’t seem like there was a solution for my application. 

How do I access the default Monolog handlers? And will those enable me to set the log levels in the STDOUT output from the rr binary?

**Comment by wolfy-j** [comment]
You can’t control the log level in rr stderr at the moment, we will need new api for that. As for monolog - https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md

You can send the output to file (do not use ex lock!).

**Comment by l0gicgate** [comment]
Okay great thank you @wolfy-j

**Comment by andrei-dascalu** [comment]
I'm having a similar issue in that I'm able to format my logs as I need them with Monolog formatters and processors but:

1. RR wraps all my logs in warnings regardless of level. This is a dealbreaker since I need my logs in stderr/stdout to be JSON but due to RR wrapping my messages, they come out escaped so my log shipper loses all my extra data.
2. I can't use files at all (I am using Kubernetes and I'm counting on the global log collector that picks up stderr by default. Sure, there are workarounds like symlinking stderr to those files and making sure I'm not lograting them, but it's a bit of headache and limits flexibility.

It would be great to separate RR logs from application logs so that stderr from application is left as-is (a nice cookie would be if a logformat env value would be made available to the app so that applications could have a pointer for matching output type - eg: if RR is set to log json, the app would be made aware of the platform setting).

**Comment by 48d90782** [comment]
@andrei-dascalu Thanks for the comment. This issue will be solved in RoadRunner 2.0 with our new container [Endure](https://github.com/spiral/endure). In this case, we will provide some basic logger which could be easily overloaded by the user.

**Comment by 48d90782** [comment]
Closed via #378
