### ISSUE TITLE
[FEATURE REQUEST] Customization of behavior when rr is unable to allocate worker

### ISSUE THREAD

**Issue by jjsaunier** [spiral/roadrunner#471]
:wave: @48d90782

follow up after discord discussion 

**Goal** : Distinct error from worker allocation to be able to retry on another rr instance at load balancer level. 

**Current State** : When rr is not able to allocate a worker, it's send a 500, which is not the best option because application that rr serve could also send 500 HTTP code. 

IHMO, rr should give the possibilty to the user to:
- send a 504 - Gateway Timeout (recoverable) 
- send a 502 Bad Gateway (not recoverable)
- Close the connection without responding (In my mind, traefik retry middleware work in this way) - https://doc.traefik.io/traefik/middlewares/retry/#:~:text=The%20Retry%20middleware%20is%20in,regardless%20of%20the%20response%20status.

With this 3 possibilities I think we good, if you see / have another use case, don't hesitate

https://github.com/spiral/roadrunner/blob/5dc83ef5eee77f4d1ef557e5f8b566e75892680d/service/http/handler.go#L134-L151

**Comment by 48d90782** [comment]
:wave:  @jjsaunier
I quite agree with your proposal. I'll think about implementation because there is not only an `"allocate worker"` error that can be returned from the `pool.Exec` method. There are also `fmt.Errorf("payload can not be empty")`, `fmt.Errorf("worker is not ready (%s)", w.state.String())` and may be more.
I think that it is better to distinct all RR errors from the errors which come from the PHP.
As for the fast solution, that you can do on your own - is to temporarily replace `w.WriteHeader(500)` with `w.WriteHeader(502)` or `504` and then build docker image (`docker build -t roadrunner:local -f Dockerfile .`) or invoke `make build` target in the Makefile.

**Comment by jjsaunier** [comment]
Indeed, i'm only experiencing the issue with `allocate worker`, so no experience on  `payload can not be empty`, `worker is not ready` but sounds good to dissociate all rr error vs app error :+1: 

Thanks for the quick solution, unfortunately traefik (which I'm using) does not support retry based on status code at this time... (I hope a day it will!) 

So currently my trick to let traefik retrying, I close the connection without responding : 

```go
hj, ok := w.(http.Hijacker)

if !ok {
	http.Error(w, "", http.StatusGatewayTimeout)
	return
}
		
conn, _, err := hj.Hijack()
conn.Close()
```

**Comment by 48d90782** [comment]
@jjsaunier https://github.com/spiral/roadrunner/pull/472
1.9.2 milestone

**Comment by jjsaunier** [comment]
You rocks @48d90782! :1st_place_medal: 

Left comment on pr

**Comment by 48d90782** [comment]
@jjsaunier https://github.com/spiral/roadrunner/releases/tag/v1.9.2

**Comment by wolfy-j** [comment]
I believe we will need to add the same thing for RR2 down the road.
